name: Java CI (Banco) com Maven

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # ADICIONADO: Garante que a token tenha permissão para segurança
    permissions:
      contents: write
      security-events: write

    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Configurar o JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: 3. Construir, Testar e Instalar (Executa Testes Unitários)
        run: mvn -B install

      - name: 4. Publicar Relatórios de Teste (Resultados do Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatórios de Teste Unitário
          path: target/surefire-reports
          retention-days: 5

      - name: 5. Atualizar Gráfico de Dependências
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6